export const EXERCISE_DB = [
  {
    "name": "Bodyweight Squats",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Squat",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Goblet Squat",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Squat",
    "goalTags": ["general_fitness", "muscle_gain", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Front Squat",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": ["Glutes", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "rack"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Back Squat",
    "primaryMuscle": ["Legs", "Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "rack"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Split Squat",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "bench", "dumbbells"],
    "pattern": "Split Squat",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Hack Squat",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": ["Glutes", "Hamstrings"],
    "type": "Machine",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Leg Press",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Hamstrings"],
    "type": "Machine",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Wall Sit",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": ["Glutes"],
    "type": "Isometric",
    "difficulty": 1,
    "equipment": ["bodyweight", "dumbbells"],
    "pattern": "Static Hold",
    "goalTags": ["endurance", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Box Squat",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "box"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Smith Machine Squat",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Pause Squat",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": ["Glutes", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "rack"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Sissy Squat",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 3,
    "equipment": ["bodyweight", "machine"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Zercher Squat",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Core", "Glutes"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Squat",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Dumbbell RDL",
    "primaryMuscle": ["Hamstrings", "Glutes"],
    "secondaryMuscle": ["Lower Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Conventional Deadlift",
    "primaryMuscle": ["Posterior Chain", "Back", "Glutes", "Hamstrings"],
    "secondaryMuscle": ["Traps", "Core", "Quads"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Sumo Deadlift",
    "primaryMuscle": ["Posterior Chain", "Glutes", "Hamstrings"],
    "secondaryMuscle": ["Adductors", "Traps"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Good Morning",
    "primaryMuscle": ["Hamstrings", "Glutes"],
    "secondaryMuscle": ["Lower Back"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Glute Bridge",
    "primaryMuscle": ["Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Bridge",
    "goalTags": ["general_fitness", "muscle_gain", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Hip Thrust",
    "primaryMuscle": ["Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "bench"],
    "pattern": "Bridge",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Cable Pull-Through",
    "primaryMuscle": ["Glutes", "Hamstrings"],
    "secondaryMuscle": ["Lower Back"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Stiff-Leg Deadlift",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": ["Glutes", "Lower Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Trap Bar Deadlift",
    "primaryMuscle": ["Posterior Chain", "Hamstrings", "Glutes"],
    "secondaryMuscle": ["Quads", "Traps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["trap_bar"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Single-Leg RDL",
    "primaryMuscle": ["Hamstrings", "Glutes"],
    "secondaryMuscle": ["Core", "Lower Back"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Lying Leg Curl",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Seated Leg Curl",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Nordic Hamstring Curl",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": ["Glutes"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "endurance"],
    "isCardio": false
  },
  {
    "name": "Single-Leg Hip Thrust",
    "primaryMuscle": ["Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "dumbbells", "bench"],
    "pattern": "Bridge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Deficit Deadlift",
    "primaryMuscle": ["Posterior Chain", "Hamstrings", "Glutes", "Back"],
    "secondaryMuscle": ["Quads", "Traps"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Forward Lunge",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Lunge",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Walking Lunge",
    "primaryMuscle": ["Legs", "Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bodyweight"],
    "pattern": "Lunge",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Step-up",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench", "bodyweight"],
    "pattern": "Step",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Curtsy Lunge",
    "primaryMuscle": ["Glutes", "Adductors"],
    "secondaryMuscle": ["Quads"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "dumbbells"],
    "pattern": "Lunge",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Lateral Lunge",
    "primaryMuscle": ["Adductors", "Quads"],
    "secondaryMuscle": ["Glutes"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "dumbbells"],
    "pattern": "Lunge",
    "goalTags": ["general_fitness", "flexibility"],
    "isCardio": false
  },
  {
    "name": "Deficit Reverse Lunge",
    "primaryMuscle": ["Glutes", "Quads"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Lunge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Goblet Lunge",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Lunge",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Stationary Lunge",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Hamstrings"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight", "dumbbells"],
    "pattern": "Lunge",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Hip Abduction Machine",
    "primaryMuscle": ["Glutes", "Abductors"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Abduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Hip Adduction Machine",
    "primaryMuscle": ["Adductors"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Adduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Copenhagen Plank",
    "primaryMuscle": ["Adductors", "Core"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 3,
    "equipment": ["bodyweight", "bench"],
    "pattern": "Static Hold",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Cable Hip Abduction",
    "primaryMuscle": ["Glutes", "Abductors"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Abduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Standing Calf Raises",
    "primaryMuscle": ["Calves"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight", "machine"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Seated Calf Raises",
    "primaryMuscle": ["Calves"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Donkey Calf Raises",
    "primaryMuscle": ["Calves"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["bodyweight", "machine"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Single-Leg Calf Raises",
    "primaryMuscle": ["Calves"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Calf Press on Leg Press",
    "primaryMuscle": ["Calves"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Push-up",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Horizontal Push",
    "goalTags": ["general_fitness", "endurance", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Wide Push-up",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Horizontal Push",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Incline Push-up",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight", "bench"],
    "pattern": "Incline Press",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Bench Press",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "bench", "rack"],
    "pattern": "Horizontal Push",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Bench Press",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Horizontal Push",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Incline Bench Press",
    "primaryMuscle": ["Upper Chest", "Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "bench", "rack"],
    "pattern": "Incline Press",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Decline Bench Press",
    "primaryMuscle": ["Lower Chest", "Chest"],
    "secondaryMuscle": ["Triceps"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "bench", "rack"],
    "pattern": "Decline Press",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Chest Fly",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "cable", "bench"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Pec Deck",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Incline Dumbbell Press",
    "primaryMuscle": ["Upper Chest", "Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Incline Press",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Decline Dumbbell Press",
    "primaryMuscle": ["Lower Chest", "Chest"],
    "secondaryMuscle": ["Triceps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Decline Press",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Decline Push-up",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "bench"],
    "pattern": "Decline Press",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Diamond Push-up",
    "primaryMuscle": ["Chest", "Triceps"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Horizontal Push",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Cable Crossover",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Low Cable Crossover",
    "primaryMuscle": ["Lower Chest", "Chest"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "High Cable Crossover",
    "primaryMuscle": ["Upper Chest", "Chest"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Pullover",
    "primaryMuscle": ["Chest", "Lats"],
    "secondaryMuscle": ["Triceps", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Machine Chest Press",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Horizontal Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Overhead Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Upper Chest", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "dumbbells", "rack"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Seated Dumbbell Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Upper Chest"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Arnold Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Upper Chest"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Lateral Raise",
    "primaryMuscle": ["Shoulders", "Side Delts"],
    "secondaryMuscle": ["Traps"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "cable"],
    "pattern": "Abduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Front Raise",
    "primaryMuscle": ["Shoulders", "Front Delts"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Rear Delt Fly",
    "primaryMuscle": ["Rear Delts", "Shoulders"],
    "secondaryMuscle": ["Traps"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "machine"],
    "pattern": "Horizontal Abduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Upright Row",
    "primaryMuscle": ["Traps", "Shoulders"],
    "secondaryMuscle": ["Biceps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "cable", "dumbbells"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Military Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Core", "Upper Chest"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Pike Push-up",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Vertical Push",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Machine Shoulder Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Cable Lateral Raise",
    "primaryMuscle": ["Shoulders", "Side Delts"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Abduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Reverse Pec Deck",
    "primaryMuscle": ["Rear Delts"],
    "secondaryMuscle": ["Traps"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Horizontal Abduction",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Bent-Over Lateral Raise",
    "primaryMuscle": ["Rear Delts"],
    "secondaryMuscle": ["Traps", "Rhomboids"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["dumbbells"],
    "pattern": "Horizontal Abduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Cable Front Raise",
    "primaryMuscle": ["Front Delts", "Shoulders"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Landmine Press",
    "primaryMuscle": ["Shoulders", "Upper Chest"],
    "secondaryMuscle": ["Triceps", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Face Pull",
    "primaryMuscle": ["Rear Delts", "Rotator Cuff"],
    "secondaryMuscle": ["Traps", "Rhomboids"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Tricep Dips",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": ["Chest", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Close-Grip Bench Press",
    "primaryMuscle": ["Triceps", "Chest"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "bench", "rack"],
    "pattern": "Horizontal Push",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Overhead Tricep Extension",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["dumbbells", "cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Rope Pushdown",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Skull Crushers",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 3,
    "equipment": ["barbell", "dumbbells", "bench"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "V-Bar Pushdown",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Single-Arm Tricep Extension",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["dumbbells", "cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Bench Dips",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": ["Chest", "Shoulders"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bench", "bodyweight"],
    "pattern": "Vertical Push",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Cable Overhead Extension",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Pull-Up",
    "primaryMuscle": ["Lats", "Back"],
    "secondaryMuscle": ["Biceps", "Rear Delts", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Chin-Up",
    "primaryMuscle": ["Lats", "Biceps"],
    "secondaryMuscle": ["Back", "Rear Delts"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Assisted Pull-Up",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Biceps", "Back"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine", "resistance_bands"],
    "pattern": "Vertical Pull",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Lat Pulldown",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Straight Arm Pulldown",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Triceps"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Wide-Grip Pull-up",
    "primaryMuscle": ["Lats", "Back"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Neutral Grip Pull-up",
    "primaryMuscle": ["Lats", "Biceps"],
    "secondaryMuscle": ["Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Close-Grip Lat Pulldown",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Biceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Underhand Lat Pulldown",
    "primaryMuscle": ["Lats", "Biceps"],
    "secondaryMuscle": ["Back"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Wide-Grip Lat Pulldown",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Rear Delts", "Biceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "V-Bar Pulldown",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Biceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Seated Row",
    "primaryMuscle": ["Back", "Lats", "Rhomboids"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Barbell Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "T-Bar Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Inverted Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Horizontal Pull",
    "goalTags": ["general_fitness", "endurance", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Pendlay Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Chest-Supported Row",
    "primaryMuscle": ["Back", "Rhomboids"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["machine", "bench", "dumbbells"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Single-Arm Dumbbell Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Cable Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Single-Arm Cable Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Machine Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Meadows Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Yates Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Lower Back"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Barbell Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Hammer Curl",
    "primaryMuscle": ["Biceps", "Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Neutral Grip Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Preacher Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["machine", "bench", "barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Concentration Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Cable Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "EZ-Bar Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Incline Dumbbell Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Spider Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["bench", "dumbbells", "barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Reverse Curl",
    "primaryMuscle": ["Forearms", "Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Zottman Curl",
    "primaryMuscle": ["Biceps", "Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Barbell Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Farmer's Carry",
    "primaryMuscle": ["Traps", "Core", "Grip"],
    "secondaryMuscle": ["Forearms", "Legs"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["general_fitness", "endurance", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Rack Pull",
    "primaryMuscle": ["Posterior Chain", "Traps", "Back"],
    "secondaryMuscle": ["Hamstrings", "Glutes", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Cable Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Smith Machine Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Wrist Curl",
    "primaryMuscle": ["Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Reverse Wrist Curl",
    "primaryMuscle": ["Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Plank",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Shoulders", "Glutes"],
    "type": "Isometric",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "endurance", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Ab Wheel Rollout",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Shoulders", "Lats"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Side Plank",
    "primaryMuscle": ["Core", "Obliques"],
    "secondaryMuscle": ["Glutes", "Shoulders"],
    "type": "Isometric",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Lateral Flexion",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Dead Bug",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "flexibility"],
    "isCardio": false
  },
  {
    "name": "Bird Dog",
    "primaryMuscle": ["Core", "Glutes"],
    "secondaryMuscle": ["Shoulders", "Hamstrings"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "flexibility"],
    "isCardio": false
  },
  {
    "name": "Hollow Body Hold",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Isometric",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Crunch",
    "primaryMuscle": ["Abs"],
    "secondaryMuscle": ["Core"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Sit-Up",
    "primaryMuscle": ["Abs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Cable Crunch",
    "primaryMuscle": ["Abs"],
    "secondaryMuscle": ["Core"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Hanging Leg Raise",
    "primaryMuscle": ["Abs", "Lower Abs"],
    "secondaryMuscle": ["Hip Flexors", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "V-Up",
    "primaryMuscle": ["Abs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Russian Twist",
    "primaryMuscle": ["Obliques", "Core"],
    "secondaryMuscle": ["Abs"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight", "dumbbells", "barbell"],
    "pattern": "Rotation",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Bicycle Crunch",
    "primaryMuscle": ["Core", "Obliques", "Abs"],
    "secondaryMuscle": [],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Rotation",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Pallof Press",
    "primaryMuscle": ["Core", "Obliques"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable", "resistance_bands"],
    "pattern": "Anti-Rotation",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Dragon Flag",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Lats", "Hip Flexors"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bench", "bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Burpee",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Chest", "Legs", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Explosive",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 10
  },
  {
    "name": "Jump Squat",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Plyometric",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 9
  },
  {
    "name": "Box Jump",
    "primaryMuscle": ["Legs", "Quads"],
    "secondaryMuscle": ["Glutes", "Calves"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Plyometric",
    "goalTags": ["endurance", "general_fitness", "weight_loss"],
    "isCardio": true,
    "caloriesPerMin": 9
  },
  {
    "name": "Mountain Climber",
    "primaryMuscle": ["Core", "Legs"],
    "secondaryMuscle": ["Shoulders", "Chest"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Dynamic",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 11
  },
  {
    "name": "High Knees",
    "primaryMuscle": ["Legs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Dynamic",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 10
  },
  {
    "name": "Jumping Jacks",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Shoulders", "Legs"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Dynamic",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 8
  },
  {
    "name": "Bear Crawl",
    "primaryMuscle": ["Core", "Shoulders"],
    "secondaryMuscle": ["Legs", "Arms"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Locomotion",
    "goalTags": ["endurance", "general_fitness", "weight_loss"],
    "isCardio": true,
    "caloriesPerMin": 8
  },
  {
    "name": "Sprint",
    "primaryMuscle": ["Legs", "Core"],
    "secondaryMuscle": ["Glutes", "Hamstrings"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Locomotion",
    "goalTags": ["endurance", "weight_loss"],
    "isCardio": true,
    "caloriesPerMin": 14
  },
  {
    "name": "Sled Push",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Legs", "Core", "Chest"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 12
  },
  {
    "name": "Battle Ropes",
    "primaryMuscle": ["Shoulders", "Core"],
    "secondaryMuscle": ["Arms", "Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 10
  },
  {
    "name": "Rowing Machine",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Back", "Legs", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 9
  },
  {
    "name": "Assault Bike",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Legs", "Shoulders", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 12
  },
  {
    "name": "Jump Rope",
    "primaryMuscle": ["Calves", "Legs"],
    "secondaryMuscle": ["Shoulders", "Core"],
    "type": "Dynamic",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Plyometric",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 12
  },
  {
    "name": "Kettlebell Swing",
    "primaryMuscle": ["Posterior Chain", "Glutes", "Hamstrings"],
    "secondaryMuscle": ["Core", "Shoulders", "Back"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["kettlebell"],
    "pattern": "Hinge",
    "goalTags": ["endurance", "weight_loss", "muscle_gain", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 9
  },
  {
    "name": "Thruster",
    "primaryMuscle": ["Full Body", "Legs", "Shoulders"],
    "secondaryMuscle": ["Core", "Triceps"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Compound Movement",
    "goalTags": ["endurance", "weight_loss", "muscle_gain"],
    "isCardio": true,
    "caloriesPerMin": 10
  },
  {
    "name": "Wall Ball",
    "primaryMuscle": ["Full Body", "Legs"],
    "secondaryMuscle": ["Core", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Explosive",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 10
  },
  {
    "name": "Turkish Get-Up",
    "primaryMuscle": ["Full Body", "Core"],
    "secondaryMuscle": ["Shoulders", "Legs", "Glutes"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["kettlebell", "dumbbells"],
    "pattern": "Complex Movement",
    "goalTags": ["general_fitness", "muscle_gain", "endurance"],
    "isCardio": false
  },
  {
    "name": "Clean and Press",
    "primaryMuscle": ["Full Body", "Shoulders"],
    "secondaryMuscle": ["Legs", "Back", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Olympic Lift",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Power Clean",
    "primaryMuscle": ["Full Body", "Back"],
    "secondaryMuscle": ["Legs", "Shoulders", "Core"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Olympic Lift",
    "goalTags": ["muscle_gain", "endurance"],
    "isCardio": false
  },
  {
    "name": "Hang Clean",
    "primaryMuscle": ["Full Body", "Back"],
    "secondaryMuscle": ["Legs", "Shoulders"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Olympic Lift",
    "goalTags": ["muscle_gain", "endurance"],
    "isCardio": false
  },
  {
    "name": "Snatch",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Shoulders", "Back", "Legs"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Olympic Lift",
    "goalTags": ["muscle_gain", "endurance"],
    "isCardio": false
  },
  {
    "name": "21s",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Barbell Kelso Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": ["Rhomboids"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell", "bench"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Bayesian Curl",
    "primaryMuscle": ["Biceps", "Forearms"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable", "dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Behind-the-Back Wrist Curl",
    "primaryMuscle": ["Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Body Saw",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Cross-Body Hammer Curl",
    "primaryMuscle": ["Biceps", "Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Neutral Grip Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Decline Sit-up",
    "primaryMuscle": ["Abs"],
    "secondaryMuscle": ["Hip Flexors", "Core"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["bench", "bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Drag Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell", "dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Face Pull to External Rotation",
    "primaryMuscle": ["Rear Delts", "Rotator Cuff"],
    "secondaryMuscle": ["Traps", "Rhomboids"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["cable"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Hanging Knee Raise",
    "primaryMuscle": ["Abs", "Lower Abs"],
    "secondaryMuscle": ["Hip Flexors", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "JM Press",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": ["Chest"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell", "bench"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Knee Raise",
    "primaryMuscle": ["Lower Abs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Leg Raise",
    "primaryMuscle": ["Lower Abs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Lying Leg Raise",
    "primaryMuscle": ["Lower Abs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Medicine Ball Slam",
    "primaryMuscle": ["Core", "Shoulders"],
    "secondaryMuscle": ["Back", "Legs"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Explosive",
    "goalTags": ["endurance", "weight_loss", "general_fitness"],
    "isCardio": true,
    "caloriesPerMin": 10
  },
  {
    "name": "Oblique Crunch",
    "primaryMuscle": ["Obliques"],
    "secondaryMuscle": ["Core"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Overhead Carry",
    "primaryMuscle": ["Core", "Shoulders"],
    "secondaryMuscle": ["Triceps", "Traps"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["general_fitness", "endurance", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Pallof Hold",
    "primaryMuscle": ["Core", "Obliques"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isometric",
    "difficulty": 2,
    "equipment": ["cable", "resistance_bands"],
    "pattern": "Anti-Rotation",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Plank to Pike",
    "primaryMuscle": ["Core", "Shoulders"],
    "secondaryMuscle": ["Abs", "Hamstrings"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Dynamic",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Plank with Shoulder Taps",
    "primaryMuscle": ["Core"],
    "secondaryMuscle": ["Shoulders", "Abs"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Rotation",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "RKC Plank",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Glutes", "Shoulders"],
    "type": "Isometric",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Romanian Deadlift (RDL)",
    "primaryMuscle": ["Posterior Chain", "Hamstrings", "Glutes"],
    "secondaryMuscle": ["Lower Back", "Traps"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Single-Arm Farmer's Carry",
    "primaryMuscle": ["Core", "Obliques", "Traps"],
    "secondaryMuscle": ["Forearms", "Legs"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["general_fitness", "endurance", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Suitcase Carry",
    "primaryMuscle": ["Core", "Obliques"],
    "secondaryMuscle": ["Traps", "Forearms"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Svend Press",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["barbell"],
    "pattern": "Isometric Press",
    "goalTags": ["muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Toe Touch",
    "primaryMuscle": ["Abs", "Core"],
    "secondaryMuscle": ["Hamstrings"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "flexibility"],
    "isCardio": false
  },
  {
    "name": "Tuck Crunch",
    "primaryMuscle": ["Abs", "Core"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Windshield Wiper",
    "primaryMuscle": ["Core", "Obliques"],
    "secondaryMuscle": ["Hip Flexors", "Lats"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight", "pull_up_bar"],
    "pattern": "Rotation",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Woodchopper",
    "primaryMuscle": ["Obliques", "Core"],
    "secondaryMuscle": ["Shoulders", "Legs"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["cable", "dumbbells"],
    "pattern": "Rotation",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  }
,
  {
    "name": "Incline Barbell Bench Press",
    "primaryMuscle": ["Upper Chest", "Chest"],
    "secondaryMuscle": ["Shoulders", "Triceps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "bench", "rack"],
    "pattern": "Incline Press",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Incline Dumbbell Bench Press",
    "primaryMuscle": ["Upper Chest", "Chest"],
    "secondaryMuscle": ["Shoulders", "Triceps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Incline Press",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Decline Barbell Bench Press",
    "primaryMuscle": ["Lower Chest", "Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell", "bench", "rack"],
    "pattern": "Decline Press",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Decline Dumbbell Press",
    "primaryMuscle": ["Lower Chest", "Chest"],
    "secondaryMuscle": ["Triceps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Decline Press",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Cable Chest Fly",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Shoulders"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Pec Deck Machine",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": [],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Horizontal Adduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Chest Dip",
    "primaryMuscle": ["Chest", "Lower Chest"],
    "secondaryMuscle": ["Triceps", "Shoulders"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Decline Press",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Chest Press",
    "primaryMuscle": ["Chest"],
    "secondaryMuscle": ["Shoulders", "Triceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Horizontal Push",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Row",
    "primaryMuscle": ["Back", "Lats"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Horizontal Pull",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Pull Apart",
    "primaryMuscle": ["Rear Delts", "Upper Back"],
    "secondaryMuscle": ["Rotator Cuff"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Horizontal Pull",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Squat",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Squat",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Deadlift",
    "primaryMuscle": ["Glutes", "Hamstrings"],
    "secondaryMuscle": ["Back", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Hinge",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Bicep Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Flexion",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Resistance Band Lateral Walk",
    "primaryMuscle": ["Glutes", "Hip Abductors"],
    "secondaryMuscle": ["Quads"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["resistance_bands"],
    "pattern": "Abduction",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Cat-Cow Stretch",
    "primaryMuscle": ["Spine", "Core"],
    "secondaryMuscle": ["Back"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Downward Dog",
    "primaryMuscle": ["Hamstrings", "Calves", "Shoulders"],
    "secondaryMuscle": ["Back", "Core"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Pigeon Pose",
    "primaryMuscle": ["Hip Flexors", "Glutes"],
    "secondaryMuscle": ["IT Band"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility"],
    "isCardio": false
  },
  {
    "name": "Hip Flexor Stretch",
    "primaryMuscle": ["Hip Flexors"],
    "secondaryMuscle": ["Quads"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Seated Hamstring Stretch",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": ["Lower Back"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Shoulder Cross Stretch",
    "primaryMuscle": ["Shoulders", "Rear Delts"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Chest Opener Stretch",
    "primaryMuscle": ["Chest", "Shoulders"],
    "secondaryMuscle": ["Biceps"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Thoracic Rotation",
    "primaryMuscle": ["Spine", "Core"],
    "secondaryMuscle": ["Obliques"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "World's Greatest Stretch",
    "primaryMuscle": ["Hip Flexors", "Thoracic Spine", "Hamstrings"],
    "secondaryMuscle": ["Glutes", "Shoulders"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Foam Roll Quads",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": ["IT Band"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Mobility",
    "goalTags": ["flexibility", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Sumo Deadlift",
    "primaryMuscle": ["Glutes", "Hamstrings", "Inner Thighs"],
    "secondaryMuscle": ["Back", "Quads"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Trap Bar Deadlift",
    "primaryMuscle": ["Glutes", "Hamstrings", "Quads"],
    "secondaryMuscle": ["Back", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["trap_bar"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Single Leg Deadlift",
    "primaryMuscle": ["Hamstrings", "Glutes"],
    "secondaryMuscle": ["Core", "Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "bodyweight"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Kettlebell Swing",
    "primaryMuscle": ["Glutes", "Hamstrings"],
    "secondaryMuscle": ["Core", "Shoulders", "Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["kettlebell"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Kettlebell Goblet Squat",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Core", "Hamstrings"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["kettlebell"],
    "pattern": "Squat",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Kettlebell Clean and Press",
    "primaryMuscle": ["Shoulders", "Glutes", "Core"],
    "secondaryMuscle": ["Triceps", "Back", "Hamstrings"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["kettlebell"],
    "pattern": "Olympic Lift",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Lateral Raise",
    "primaryMuscle": ["Shoulders", "Side Delts"],
    "secondaryMuscle": ["Traps"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Abduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Cable Lateral Raise",
    "primaryMuscle": ["Shoulders", "Side Delts"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Abduction",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Arnold Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Upper Chest"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Seated Dumbbell Shoulder Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps", "Upper Chest"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["dumbbells", "bench"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Machine Shoulder Press",
    "primaryMuscle": ["Shoulders"],
    "secondaryMuscle": ["Triceps"],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Front Raise",
    "primaryMuscle": ["Shoulders", "Front Delts"],
    "secondaryMuscle": ["Upper Chest"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "barbell", "cable"],
    "pattern": "Vertical Push",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Reverse Fly",
    "primaryMuscle": ["Rear Delts", "Upper Back"],
    "secondaryMuscle": ["Rhomboids", "Traps"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "cable", "machine"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Hammer Curl",
    "primaryMuscle": ["Biceps", "Brachialis"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Preacher Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["barbell", "dumbbells", "machine"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Cable Curl",
    "primaryMuscle": ["Biceps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Skull Crusher",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["barbell", "dumbbells", "bench"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Cable Tricep Pushdown",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Overhead Tricep Extension",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "cable", "barbell"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Tricep Kickback",
    "primaryMuscle": ["Triceps"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "cable"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Leg Extension",
    "primaryMuscle": ["Quads"],
    "secondaryMuscle": [],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Leg Curl",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": [],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Nordic Hamstring Curl",
    "primaryMuscle": ["Hamstrings"],
    "secondaryMuscle": ["Glutes"],
    "type": "Compound",
    "difficulty": 3,
    "equipment": ["bodyweight"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Hip Thrust",
    "primaryMuscle": ["Glutes"],
    "secondaryMuscle": ["Hamstrings", "Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["barbell", "dumbbells", "bench"],
    "pattern": "Bridge",
    "goalTags": ["muscle_gain", "general_fitness", "weight_loss"],
    "isCardio": false
  },
  {
    "name": "Cable Pull Through",
    "primaryMuscle": ["Glutes", "Hamstrings"],
    "secondaryMuscle": ["Core"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Hinge",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Seated Calf Raise",
    "primaryMuscle": ["Calves", "Soleus"],
    "secondaryMuscle": [],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Donkey Calf Raise",
    "primaryMuscle": ["Calves"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine", "bodyweight"],
    "pattern": "Plantar Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "T-Bar Row",
    "primaryMuscle": ["Back", "Lats", "Rhomboids"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["barbell"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Chest Supported Row",
    "primaryMuscle": ["Back", "Rhomboids", "Rear Delts"],
    "secondaryMuscle": ["Biceps"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["dumbbells", "machine", "bench"],
    "pattern": "Horizontal Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Lat Pulldown",
    "primaryMuscle": ["Lats", "Back"],
    "secondaryMuscle": ["Biceps", "Rear Delts"],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Close Grip Lat Pulldown",
    "primaryMuscle": ["Lats", "Back"],
    "secondaryMuscle": ["Biceps"],
    "type": "Machine",
    "difficulty": 1,
    "equipment": ["cable", "machine"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Straight Arm Pulldown",
    "primaryMuscle": ["Lats"],
    "secondaryMuscle": ["Triceps", "Core"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable"],
    "pattern": "Vertical Pull",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Plank",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Shoulders", "Glutes"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Side Plank",
    "primaryMuscle": ["Obliques", "Core"],
    "secondaryMuscle": ["Shoulders", "Glutes"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "weight_loss", "endurance"],
    "isCardio": false
  },
  {
    "name": "Dead Bug",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "flexibility"],
    "isCardio": false
  },
  {
    "name": "Hollow Body Hold",
    "primaryMuscle": ["Abs", "Core"],
    "secondaryMuscle": ["Hip Flexors"],
    "type": "Isolation",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["general_fitness", "muscle_gain"],
    "isCardio": false
  },
  {
    "name": "Mountain Climber",
    "primaryMuscle": ["Core", "Abs"],
    "secondaryMuscle": ["Shoulders", "Hip Flexors", "Quads"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["bodyweight"],
    "pattern": "Dynamic",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Burpee",
    "primaryMuscle": ["Full Body"],
    "secondaryMuscle": ["Chest", "Shoulders", "Quads", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Dynamic",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Box Jump",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Calves"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["box"],
    "pattern": "Plyometric",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Jump Squat",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Calves", "Core"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["bodyweight"],
    "pattern": "Plyometric",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Battle Ropes",
    "primaryMuscle": ["Shoulders", "Core"],
    "secondaryMuscle": ["Arms", "Back"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["weight_loss", "endurance"],
    "isCardio": true
  },
  {
    "name": "Rowing Machine",
    "primaryMuscle": ["Back", "Legs"],
    "secondaryMuscle": ["Core", "Shoulders", "Arms"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Stationary Bike",
    "primaryMuscle": ["Quads", "Calves"],
    "secondaryMuscle": ["Glutes", "Hamstrings"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Stair Climber",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Calves"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Elliptical",
    "primaryMuscle": ["Quads", "Glutes"],
    "secondaryMuscle": ["Hamstrings", "Calves", "Shoulders"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["machine"],
    "pattern": "Conditioning",
    "goalTags": ["weight_loss", "endurance", "general_fitness"],
    "isCardio": true
  },
  {
    "name": "Farmer Carry",
    "primaryMuscle": ["Forearms", "Traps"],
    "secondaryMuscle": ["Core", "Glutes", "Quads"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["muscle_gain", "general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Suitcase Carry",
    "primaryMuscle": ["Core", "Obliques", "Forearms"],
    "secondaryMuscle": ["Traps", "Glutes"],
    "type": "Compound",
    "difficulty": 1,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Overhead Carry",
    "primaryMuscle": ["Shoulders", "Core"],
    "secondaryMuscle": ["Triceps", "Traps"],
    "type": "Compound",
    "difficulty": 2,
    "equipment": ["dumbbells", "kettlebell"],
    "pattern": "Carry",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Dumbbell Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": ["Neck"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Barbell Shrug",
    "primaryMuscle": ["Traps"],
    "secondaryMuscle": ["Forearms"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["barbell"],
    "pattern": "Elevation",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Wrist Curl",
    "primaryMuscle": ["Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "barbell"],
    "pattern": "Flexion",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Reverse Wrist Curl",
    "primaryMuscle": ["Forearms"],
    "secondaryMuscle": [],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["dumbbells", "barbell"],
    "pattern": "Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  },
  {
    "name": "Pallof Press",
    "primaryMuscle": ["Core", "Obliques"],
    "secondaryMuscle": ["Shoulders", "Chest"],
    "type": "Isolation",
    "difficulty": 1,
    "equipment": ["cable", "resistance_bands"],
    "pattern": "Anti-Rotation",
    "goalTags": ["general_fitness", "endurance"],
    "isCardio": false
  },
  {
    "name": "Copenhagen Plank",
    "primaryMuscle": ["Hip Adductors", "Core"],
    "secondaryMuscle": ["Obliques", "Glutes"],
    "type": "Isolation",
    "difficulty": 3,
    "equipment": ["bodyweight"],
    "pattern": "Anti-Extension",
    "goalTags": ["muscle_gain", "general_fitness"],
    "isCardio": false
  }

];

const _exerciseIndex = new Map(
  EXERCISE_DB.map((ex) => [ex.name.toLowerCase(), ex])
);

export function lookupExercise(name) {
  if (!name) return null;
  const lower = name.toLowerCase();
  const exact = _exerciseIndex.get(lower);
  if (exact) return exact;
  for (const ex of EXERCISE_DB) {
    const exLower = ex.name.toLowerCase();
    if (lower.includes(exLower) || exLower.includes(lower)) return ex;
  }
  return null;
}